### ISSUE TITLE
Wrapper incorrectly configured - double scroll bar as a result

### ISSUE THREAD

**Issue by particthistle** [joomla-projects/soc21_guided-tour#11]
Something is not formatted correctly with the page layout - it's using a wrapper class that ends up creating a double scroll bar.

![image](https://user-images.githubusercontent.com/5515866/134336940-72813d40-f66c-4a2f-87aa-97b4eddd0821.png)

**Comment by jatinS-dev** [comment]
![Guided Tour - Edit Tour - joomla - Administration - Google Chrome 9_24_2021 12_30_09 AM](https://user-images.githubusercontent.com/66058203/134567729-b8f770b7-a02b-4c94-9a5f-d672c7d632e1.png)

This is a default feature in Joomla and already implemented by other developers, has nothing to do with the wrapper, when we click on the dropdown that other scroll down disappeared.

**Comment by jatinS-dev** [comment]
https://github.com/joomla/joomla-cms/tree/4.0-dev/libraries/src/Form/Field

has taken the direct code from there for XML form -> e.g. type="Components"

**Comment by jatinS-dev** [comment]
@particthistle in this case everything is formatted and we can close this issue

**Comment by particthistle** [comment]
There should not be a double scroll bar.

I've not yet put my finger on the cause of the scroll bars, but essentially the form for Tours is the same as the form for Steps and Steps doesn't have the double scroll bar. Something with the Details tab is causing an overflow to trigger the scroll bar.

In a comparing the Tours and Steps pages, I can see subtle differences which shouldn't impact it, but are worth trying to get rid of the scroll bars before they end up getting picked up later in a code review.

Tour page currently:
![image](https://user-images.githubusercontent.com/5515866/134674670-53a7f532-757f-4bcc-9627-3d0411f97a01.png)

Steps page currently:
![image](https://user-images.githubusercontent.com/5515866/134674709-6d16338e-f92a-4e37-a371-448572e9b89c.png)

**Comment by jatinS-dev** [comment]
![1](https://user-images.githubusercontent.com/66058203/134765535-4536c9d8-c2ec-4555-8beb-ddb13f687368.png)

**Comment by jatinS-dev** [comment]
This is the reason for double scroll-bar

**Comment by jatinS-dev** [comment]
![Guided Tour - Edit Tour - joomla - Administration - Google Chrome 9_25_2021 2_09_37 PM](https://user-images.githubusercontent.com/66058203/134765550-4ffb30a6-b939-4847-8874-750f58c7bc23.png)

**Comment by jatinS-dev** [comment]
if we click on the Component Selector another scroll bar disappears.

**Comment by jatinS-dev** [comment]
![1](https://user-images.githubusercontent.com/66058203/134765636-45049db1-fdcb-4386-89e4-799738b02f12.png)

@particthistle  The same problem we get in Workflows-Transitions, due to the `Usergroup` selection

**Comment by particthistle** [comment]
Ok so this now looks to be an issue with the CSS for the Multiple Choices field type :(

I'll look into it further to try and figure out a solution and raise a PR in the main project.
