### ISSUE TITLE
Dropdown on Joomla button toolbar does not dropdown.

### ISSUE THREAD

**Issue by particthistle** [joomla-projects/soc21_guided-tour#12]
![image](https://user-images.githubusercontent.com/5515866/134337744-d5271f27-02ae-4ddf-94be-4ab2454c1053.png)

Dropdown should dropdown where indicated.

Looks like additional options that are in that menu are not configured.
* Save and New
* Save as Copy (only appears after initial save)

**Comment by jatinS-dev** [comment]
I added the option for dropdown and now the Dropdown is working with giving the option "save and new"

**Comment by jatinS-dev** [comment]
@particthistle we can close this issue now

**Comment by particthistle** [comment]
Confirmed as working on both Tours and Steps

On new Tour or Step:
![image](https://user-images.githubusercontent.com/5515866/134675210-37a2691d-e0e0-417b-8785-49a2b117dbc3.png)

On saved Tour or Step:
![image](https://user-images.githubusercontent.com/5515866/134675091-ef31dac0-ccb7-498e-a03d-0e4c7c2a6100.png)
