### ISSUE TITLE
Status not correct on List of Tours

### ISSUE THREAD

**Issue by particthistle** [joomla-projects/soc21_guided-tour#14]
![image](https://user-images.githubusercontent.com/5515866/134339264-040536b0-16de-425a-8e8d-f704c6e11845.png)

In the example screen shot:
* Tour 2 is actually unpublished (was initially published, then unpublished)
* Tour 3 is unpublished (created new tour and set it to Unpublished)

For both tours, editing the tour shows it's unpublished, but the List of Tours is not showing the tour's status correctly.

Additionally, when you click on the column heading to sort the column by Status, the sort order indicator does not change. Click on Tour name column to see the behaviour that is expected for the Status column.

**Comment by particthistle** [comment]
While modifying that view:
* Align the Steps column to left or center (see Content > Categories to see what layout is used there)
* The description column is possibly not needed on this view. The tour title is most likely self explanatory, while the description may end up quite lengthy.

![image](https://user-images.githubusercontent.com/5515866/134340091-878a1c75-7611-4edd-9835-055de807d10e.png)

**Comment by jatinS-dev** [comment]
![Guided Tour - List of Tours - joomla - Administration - Google Chrome 9_24_2021 6_06_21 PM](https://user-images.githubusercontent.com/66058203/134675253-26850533-3249-4fa6-abbc-23c646eee919.png)
![Guided Tour - List of Tours - joomla - Administration - Google Chrome 9_24_2021 6_06_36 PM](https://user-images.githubusercontent.com/66058203/134675288-828d7c62-6b8e-417a-9dca-ad1b14c42337.png)

Here is the new result

**Comment by jatinS-dev** [comment]
@particthistle we can close this issue now

**Comment by particthistle** [comment]
Not quite...

- Unpublish one (or more) tours
- Try sorting by the Status column.
- Expected behaviour: Status column heading should change to show ASC/DESC and rows should be sorted accordingly.
- Current behaviour: Status column heading does not change, rows do not sort based on status.

Also,
- Steps list: Status column on Tours page is not sorting / changing column heading
- You might not have gotten to #15 yet, with some options not applying correctly still.

**Comment by jatinS-dev** [comment]
![1](https://user-images.githubusercontent.com/66058203/134721555-9296b58c-90bd-461c-9977-2ceefb9cf4d2.png)

here is the new result

**Comment by particthistle** [comment]
Try to get a bit more thorough with your testing of scenarios please @jatinS-dev 

- Dropdown is missing options for Description and Steps
- Column heading on Steps column does not switch to indicate sort ASC/DESC when column is selected.
- Steps column is not sorting.

All the other scenarios work as expected.

**Comment by jatinS-dev** [comment]
@particthistle @bembelimen in this issue rest everything is done, but here I am not able to find a way to sort the list view based upon the `steps count`, I searched in `com_workflows` cause it has a similar structure as `com_guidedtours` like there are `stages` and here is `steps`, but there also I didn't get anything which was sorting the list based on the `stages count`.

**Comment by jatinS-dev** [comment]
@particthistle I've gone through several other components, and I found out that actually there were no previous example where they sort the link button which leads to different page, for e.g. stage and transition in com_workflow.

**Comment by jatinS-dev** [comment]
@particthistle we can close this issue

**Comment by particthistle** [comment]
I need to do another rebuild, to check if you've just left it as it was or fixed it.

If you're not implementing the ability to sort by the number of steps (it's not that useful really anyway) then you need to remove the ability to click the column heading to sort it.

**Comment by jatinS-dev** [comment]
![1](https://user-images.githubusercontent.com/66058203/135275431-a39aa628-fa52-49fb-a10e-264904578906.png)

**Comment by jatinS-dev** [comment]
@particthistle removed the ability to click the column heading to sort it.

**Comment by particthistle** [comment]
Working as expected now. Thanks.
