### ISSUE TITLE
Discussion: Multipage option selector

### ISSUE THREAD

**Issue by particthistle** [joomla-projects/soc21_guided-tour#17]
@jatinS-dev can you please explain more the detail behind the Multipage option on the Step?

If the URL is different to the previous step, wouldn't that directly trigger the multipage code?

**Comment by jatinS-dev** [comment]
@particthistle, Previously when I was implementing the Multi-Page feature, I thought keeping track of the steps which next step is on the different page will be helpful, but after the new implementation, we don't actually need this field here. So I removed it now.

**Comment by particthistle** [comment]
Good. Makes more sense.
