### ISSUE TITLE
Steps: Various Issues

### ISSUE THREAD

**Issue by particthistle** [joomla-projects/soc21_guided-tour#18]
A number of issues are happening with the Steps list view:
* ~Once #16 is resolved, the Back button on the Steps list view is not required. Expected behaviour should be similar to the relationship between Articles and Categories in the Content section.~
* ~Filter Options need to be added to Steps list to be able to filter for all steps in a particular Tour. See Articles filter for expected behaviour and other options to consider.~
* _Above point replaced by:_ The relationship between Tour and Steps needs to be improved. Look more at Workflow. (If you've not turned on Workflow @jatinS-dev to see it's functionality, go to Content > Options > Integration and turn on the component. You'll then see it under Content > Workflows.

In the Step editor view:
* You're not showing which tour the step is for. Here's what the Transitions screen looks like with the Workflow title in the page heading:
![image](https://user-images.githubusercontent.com/5515866/134762571-698257f6-3a15-4a12-bae6-84affcc02929.png)

* ~Similar to #12, Joomla button toolbar dropdown does not have options. Ability to "Save and New" and "Save as Copy" are needed.~ Resolved in #12 
* ~On resolving above two issues, you should be able to also as an example Save as Copy, then change the tour and Save the step to a different tour.~ Resolved in #12 
* ~As mentioned in #10 Overlay should be applied to a Step, not a Tour.~ Partially resolved - Overlay removed from Tour
* Steps should not need "Access" - they will inherit the Access Control Level (ACL) from the Tour as Tours and Steps have a strict relationship, so a Step shouldn't have a different ACL to the Tour.

**Comment by particthistle** [comment]
![image](https://user-images.githubusercontent.com/5515866/134677811-31a6d929-1a0c-4963-8473-72841af3c6fd.png)
If the positions are fixed in their orientation - so the classes can only be **top, right, bottom, left** orientations should this be either a dropdown or a selector? 

Or does this field add a CSS class to the tool tip, so with some documentation and creativity, developers could add additional formats?

For the URL field, the default value is https://1 - incorrect. Please resolve.

**Comment by jatinS-dev** [comment]
@particthistle added dropdown selection option for `position` selection field, and removed URL as we don't need URL field in Step-form.
![1](https://user-images.githubusercontent.com/66058203/134781331-fa584061-4977-4e22-8b28-ba482b12e877.png)

here is the new result.

**Comment by jatinS-dev** [comment]
![1](https://user-images.githubusercontent.com/66058203/134782976-615406b8-11a6-4df1-bb47-b80c85fd9067.jpg)

I added the dynamic headline functionality in the `steps list`

**Comment by jatinS-dev** [comment]
![1](https://user-images.githubusercontent.com/66058203/134783028-3655be26-0dc8-4c87-aae1-0f8a41ad0117.png)

I added the dynamic Toolbar Headline in the `steps list` view.

**Comment by jatinS-dev** [comment]
@particthistle I removed `access` from the step edit form, as you suggested.

**Comment by particthistle** [comment]
Will test on next build installation tomorrow.

**Comment by particthistle** [comment]
Confirming these items are resolved:
- Access permissions removed
- Step name in heading on edit view
- Tour name in heading on edit view
- Position list now a dropdown

Closing this issue. Raising two others for two minor improvements.
