### ISSUE TITLE
Installer: guidedtours.xml - remove Menu and Submenu; Fix other Banners related code.

### ISSUE THREAD

**Issue by particthistle** [joomla-projects/soc21_guided-tour#24]
![image](https://user-images.githubusercontent.com/5515866/134756668-849c27d5-b460-4321-a0dd-b366406df7b0.png)

Language Strings to be added:
* COM_GUIDEDTOURS - Component name
* COM_GUIDEDTOURS_XML_DESCRIPTION - Component Description
* Both required for in the plugin management screen

~Currently guidedtours.xml looks to have been based on banners.xml and still contains sub menu items for banners component.~

~Changing this will partially assist with resolving #16~

Functionality changed following code review discussion with @bembelimen 
- Installer should not create a Components menu item
- Component should only be configured and managed from System Dashboard > Manage module (installed already via system.xml)

### To Do
* Remove section of guidedtours.xml that creates the menu and submenu
* Fix guidedtours.xml with any remaining banners.xml content that needs to be removed
* Add language strings so that the component is labelled and described correctly in System > Manage > Extensions

**Comment by particthistle** [comment]
Fixing up everything in guidedtours.xml I think will resolve #16 which is where you'ved asked a question on glip where you can't match the layout to the screen shot I provided in #16.

I've just
- removed the component
- fetched the origin again from github
- went to System > Install > Discover to get the component to reinstall.
- The component then reinstalled - but with the errors due to language strings being missing and the sub menu being the one copied from banners component, you have a few issues.

![image](https://user-images.githubusercontent.com/5515866/134760373-f3b7228a-a43b-4f0f-81df-e4ec479bb954.png)

**Comment by particthistle** [comment]
Following discussion with @bembelimen, Components > Guided Tours is not required.

- guidedtours.xml should not install a menu item in components, so the XML for the menu and submenu needs to be removed.
- it should be accessed only from System > Manage > Guided Tours - which is created by the system.xml file (and is already in place)
- Language strings mentioned are not required.
- #16 will now be rewritten.
- Reinstalling the component after the changes have been made should see no Components entry for Guided Tours and no Guided Tours entry appearing in the dashboard.

_Once guidedtours.xml has been confirmed as updated, this issue will be closed._

**Comment by jatinS-dev** [comment]
@particthistle I've added the language string for "COM_GUIDEDTOURS_XML_DESCRIPTION" in the language files, but it is not showing any result though

**Comment by jatinS-dev** [comment]
I think the rest all the things are fixed for this issue

**Comment by particthistle** [comment]
COM_GUIDEDTOURS_XML_DESCRIPTION is only visible when you go to System > Manage > Extensions and filter for the Tour Extensions. 

That's now fixed.

![image](https://user-images.githubusercontent.com/5515866/134804042-64738116-59b8-40a4-87f8-5e5f2f629a27.png)

But...
* Make a note to update the version release date in the guidedtours.xml file before release.
* Check any other instances of Guided Tour and change relevant ones to Guided Tours for consistency in the language files (I've tagged some for review)

**Comment by particthistle** [comment]
This issue can be closed once this review is completed.
https://github.com/joomla-projects/soc21_guided-tour/pull/5#pullrequestreview-763681284

**Comment by jatinS-dev** [comment]
@particthistle added all the required strings in the language file.

**Comment by jatinS-dev** [comment]
@particthistle we can close this issue

**Comment by particthistle** [comment]
Checking on installing next build before closing.

**Comment by particthistle** [comment]
Confirming:
- Systems > Extensions > Manage - component and plugin names and tooltips corrected.
- Components menu items removed
- Items from banners.xml (used as base file) have been removed where they no longer apply for guidedtours.xml

Closing 👍🏻
