### ISSUE TITLE
Tour Published state not correct

### ISSUE THREAD

**Issue by particthistle** [joomla-projects/soc21_guided-tour#25]
### Steps to reproduce the issue

* Create a tour
* Set it to unpublished
* Save and close
* Tour should show as unpublished in the Tour list; ~Alias should be created on Save (or Save and Close , or Save and New, or Save as Copy - each uses the Save function)~
* Edit the tour again
* Tour is showing as Published in the edit view; Alias is empty unless it was manually entered
* Unpublished tour is also showing in the tour list

### Expected result
* ~Alias gets created on Save~
* Published status should change on the Edit View
* Published status should be reflected on the list of tours the plugin loads.

### Actual result
Unpublished tour shows correctly unpublished in the Tour list
![image](https://user-images.githubusercontent.com/5515866/134805243-18f0b4de-0348-4c4d-959d-7e14d852a428.png)

On editing the tour, Status is showing as Published. ~Also noticed that the Alias for the tour has not been created automatically on save.~
![image](https://user-images.githubusercontent.com/5515866/134805248-a9897dda-e9d1-47e1-bde0-83a5f583e357.png)

Clicking Save and close returns to the Tour List where the Tour is still displayed as published.

Unpublished tour is still appearing in the Tour dropdown.
![image](https://user-images.githubusercontent.com/5515866/134805299-68bb8aa1-c1c1-4340-a015-4f2946e0efa3.png)

**Comment by particthistle** [comment]
Same behaviour on Steps :(

**Comment by jatinS-dev** [comment]
@particthistle I added code that will filter the tours based on their published state, and I removed the alias part because I don't think we need an alias in Guided Tour Component, it will be just an unnecessary field as we are implementing based on `com_workflows`.

**Comment by particthistle** [comment]
Agreed. As you can't get to the tour via a URL, aliases I don't think apply either.

Thoughts @bembelimen?

**Comment by particthistle** [comment]
@jatinS-dev - I've confirmed with @bembelimen aliases are not required, so you can go about removing those from the various aspects of Tours (views, tables etc)

**Comment by particthistle** [comment]
@jatinS-dev if you can resolve this issue today, that would be good to be able to close tomorrow as this is one that needs to be cleared up otherwise it will be failing tests along the way to being merged.

**Comment by particthistle** [comment]
Tested and working correctly now. Nice work sorting it out.

There's one final issue, but so as to get some progress I'll raise that as a new issue and close this one.
