### ISSUE TITLE
Tour dropdown menu - bottom not formatted correctly

### ISSUE THREAD

**Issue by particthistle** [joomla-projects/soc21_guided-tour#26]
### Steps to reproduce the issue
Compare the bottom of the Actions dropdown menu to the Tours dropdown menu. The tours menu has not got the formatting set correctly.

### Expected result
The bottom of the Tours dropdown should look like the bottom of the Actions menu
![image](https://user-images.githubusercontent.com/5515866/135455530-1e0db9cd-b158-4eea-8b99-816b12e9413f.png)

### Actual result
Last item formatting is not correct.
![image](https://user-images.githubusercontent.com/5515866/135455593-c5a92ccb-a482-4bfc-9e6e-f4eb7355e08b.png)

![image](https://user-images.githubusercontent.com/5515866/135455653-7be5b56a-fa6f-48ba-9f01-e6a7b98aa063.png)

**Comment by jatinS-dev** [comment]
![1](https://user-images.githubusercontent.com/66058203/135760260-eff8a7f8-92a3-458a-b751-a51dd0e63b4b.png)

**Comment by jatinS-dev** [comment]
@particthistle this issue is fixed.

**Comment by particthistle** [comment]
CSS confirmed as fixed.
