### ISSUE TITLE
Add "Centered" to the positioning dropdown for Steps

### ISSUE THREAD

**Issue by particthistle** [joomla-projects/soc21_guided-tour#27]
### Is your feature request related to a problem? Please describe.
While looking at #18, I walked through the demo for Shepherd again. I noticed the Centered option for a step. 

See step 5 of the demo:
https://shepherdjs.dev/

isCentered function:
https://shepherdjs.dev/docs/Step.html#isCentered

### Describe the solution you'd like
Implement isCentered and add Centered as an option in the step position dropdown.

**Comment by jatinS-dev** [comment]
@particthistle isCentered() function will return bool as an output, if we want to add "Centered " Positioning option we have to give random className which is not present in the screen as an input, so by default if the Tour/Step doesn't get a proper className/ ID, the positioning will be centered then.

**Comment by particthistle** [comment]
I think having it as a specific option is better UX, as otherwise it's not clear it's actually an option.

You could add a condition where you're already looking at the position and where you're attaching the step to the target.

IF target == blank THEN isCentered.

In the step settings, add Centered as a position option, and the description on Target can be updated. You have no required validation on Target, so at the moment if there's nothing in there that's not a problem.

You could consider validation on target field, but I'm not sure how you'd go about making the validation conditional so it can only be blank if the position selected is Centered. (Noting this as something to possibly improve before 4.1 final release)

![image](https://user-images.githubusercontent.com/5515866/135711543-086a63c8-9995-40bf-86e2-cad6647df6b4.png)


At a minimum:
- Add the Centered option to the position dropdown so it can be specifically selected.
- Update the language strings to be more helpful:

**COM_GUIDEDTOURS_POSITION_DESC**
Add the Position where you want to display your step. e.g. Bottom, Top, Right, Left, Centered

**COM_GUIDEDTOURS_TARGET_DESC**
Add the target item to attach your step element to. Options: .classname, #id or leave blank for a centered step.

**COM_GUIDEDTOURS_FIELD_OPTION_CENTERED**
Add this string to allow Centered to be in the dropdown list.

**Comment by jatinS-dev** [comment]
@particthistle I've added the `Centered` Option in Step form, we can close this issue.

**Comment by particthistle** [comment]
Options and descriptions updated per request.
