### ISSUE TITLE
Language Files - Clean up .sys.ini files

### ISSUE THREAD

**Issue by particthistle** [joomla-projects/soc21_guided-tour#30]
### .sys.ini only needs to contain strings relating to the installation.

Currently
- com_guidedtours.sys,ini and com_guidedtours.ini are the same as one another
- en-GB.plg_system_tour.sys,ini  and en-GB.plg_system_tour.ini are the same as one another

.sys.ini files should only contain the files needed to display the information in the installer manager, so where there's duplicated strings across both files, the bulk of the strings should be in the .ini file only.

View pairs of files in /administrator/language/en_GB/ for example from other components.

**Comment by jatinS-dev** [comment]
@particthistle I've made some changes in language files

**Comment by particthistle** [comment]
Separation of language and optimisation between installation strings and component strings looks to be complete.
