### ISSUE TITLE
Incorrect Label for selector

### ISSUE THREAD

**Issue by particthistle** [joomla-projects/soc21_guided-tour#9]
"Plugin Selector" is inaccurate. That's more WP terminology.

Options:
* Extension Selector - more general, but the list is only components
* Component Selector - more specific if the tours are going to only be applicable in Components

![image](https://user-images.githubusercontent.com/5515866/134332809-aa0ce525-2850-4d06-bfae-e1a19568a9ba.png)

Additionally, error message does not match up with the field name matching the label.
![image](https://user-images.githubusercontent.com/5515866/134337300-ac29ef5d-a8bf-4dd3-ad5c-603bb8b9b41e.png)
_To trigger the error, delete All option on Component selector and leave it blank_

If the extensions list is blank on save, should the All default option be automatically added back in?

**Comment by jatinS-dev** [comment]
Change the name [ Plugin Selector -> Component Selector ]

**Comment by jatinS-dev** [comment]
[Overloaded store function] Added the code in TourTable.php to fix the above error message

**Comment by jatinS-dev** [comment]
The issue is fixed.

**Comment by particthistle** [comment]
> Change the name [ Plugin Selector -> Component Selector ]
![image](https://user-images.githubusercontent.com/5515866/134664702-b7052181-6587-44a3-8cde-86b52c258473.png)
Label confirmed as fixed.

> [Overloaded store function] Added the code in TourTable.php to fix the above error message

Looking at the functionality for the Component Selector field:
* I'm not sure whether All should be a default option. @jatinS-dev does this mean if All is selected, the Guided Tour button will appear for EVERY component on the site? If that is the case, I don't know that that is the desired behaviour. Perhaps there shouldn't be a default of All available?
* If you delete All as an option, and don't select another component, so the field is left blank, then you should not populate it automatically with All as the default option - an error should still be shown as the user should be prompted to action providing a selection, otherwise they may not realise they have made a mistake.
* The error message was noted by @bembelimen in handover notes, so he may have more thoughts to add.

**Comment by jatinS-dev** [comment]
@particthistle so finally do we need `all` as a default or not?

**Comment by jatinS-dev** [comment]
Cause I and Benjamin spent around 2 weeks for this feature of `all` and for the respected filtering based on the same.

**Comment by particthistle** [comment]
RFC - @bembelimen @shivamdiehard @softforge - Can you please weigh in on the default field for the tours. I don't think having Tours displayed to "All" components is good UX.

* At the moment "All" as the default I think is going to mean that for this particular tour, it would trigger the Guided Tours System Plugin to display a button for the tour on EVERY component page in the administrator area of Joomla site.
![image](https://user-images.githubusercontent.com/5515866/134804985-a7ce1aa3-7b18-44c9-92b4-fd4348cc8769.png)
* Wouldn't the preference be to only have the relevant tours available on the relevant pages? The tours I would think are like Help pages - you don't have a Help index on every page.
* If there's a default tour created for every core component, plus the user creates lots and makes them all "All", plus 3rd party developers accidentally set the tours to "All" then the plugin dropdown potentially will get very unmanageable.
* If there's no tours available for the page, then the plugin button should hide.

**Comment by jatinS-dev** [comment]
@particthistle referring to this point `If there's no tours available for the page, then the plugin button should hide.` we can do this, just have to remove the `all` as a default option. But then the thing is Users have to find the Tour from `com_guidedtours` which are not shown here directly as a result of `all`, and that's time wasting.

**Comment by particthistle** [comment]
> But then the thing is Users have to find the Tour from com_guidedtours which are not shown here directly as a result of all, and that's time wasting.

They would not really go looking for a tour if it wasn't available to them for that particular component.

Having "All" items means that the user might end up being taken away to a completely different component unnecessarily.

**Comment by jatinS-dev** [comment]
@particthistle what should be the exact result here?

**Comment by jatinS-dev** [comment]
Should I remove the default field from there?

**Comment by particthistle** [comment]
Waiting for feedback from others.

**Comment by bembelimen** [comment]
"All" is ok for default value, wouldn't waste any time here to change it.

**Comment by particthistle** [comment]
Closing.

Be sure to add a note in the documentation @jatinS-dev for this field to note that if the Tour is set to "All" it's going to appear everywhere in the back end of the site.
